---
apiVersion: v1
kind: Namespace
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        ran.openshift.io/ztp-gitops-generated: '{}'
    labels:
        name: ztp-sno
    name: ztp-sno

---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
    annotations:
        agent-install.openshift.io/install-config-overrides: '{"networking":{"networkType":"OVNKubernetes"}}'
        argocd.argoproj.io/sync-wave: "1"
        ran.openshift.io/ztp-gitops-generated: '{}'
    name: ztp-sno
    namespace: ztp-sno
spec:
    clusterDeploymentRef:
        name: ztp-sno
    imageSetRef:
        name: openshift-4.12
    manifestsConfigMapRefs:
        - name: ztp-sno
    networking:
        clusterNetwork:
            - cidr: 10.128.0.0/14
              hostPrefix: 23
        machineNetwork:
            - cidr: 192.168.235.0/24
        serviceNetwork:
            - 172.30.0.0/16
    provisionRequirements:
        controlPlaneAgents: 1
    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC3aLYapMApL1taw0SeWysvpKOJf0tklEE20UtdBlIh9/S8oOZMf7qX+57PMJ82S/9tIAWcVnGQlErMkdPozF5CUjeNwrlOUVuKlYDwbz3olUFvnwF9a3xDw7RFm1oKyBaA/69eff7qSGWULwDiVH4CRO1EVvQlOsONz/oT4hcLkJMAoCyWeKBgHfpS30kVTnk0+qh5Xu7tEwr8yf/CIfJFO1n39lP9htpnUnGXPeMfXApN0YE7XXZXt8x50DlsqfVc+1u/EaIDwSwTYH7VYba/LpS8Coa4Ox7r98kHq+VxYU3g546b7RgxCGgRFCYEnzDVW7BRM03UJJH1kOFJ1/954LomTSDVTgs7/fDhj3TmzEdKC74mE2MjuQs5HzsrHOyfswScHF5AhciXLFIy8FciJfm/+7iGfo2Kt/YUajdq9Tl6pjbmaNSSCYFxMQkPF9G2bZer0UBu1zMv5LG4r9Lrzc4wkl90O41Us7Bku983PFfwF9PTrnknDYy4vq2Mhm0vkJV8fGL9eyaZTwMmSE8W/3BOr6SY6pC//7qlHNbIbsBlTMQp2Tl6AleHOa5fbJN4D/7Ps5E+aL0aH8jdr6OMxOSrc6w1DJg5x3paZ59zqdiQ+Ybnu0Vkts7KxbKCsaPJjA5jwIL5FSoZsjUMXcdOrUyLova6/M7DYZut7qHNrQ== '

---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "1"
        ran.openshift.io/ztp-gitops-generated: '{}'
    name: ztp-sno
    namespace: ztp-sno
spec:
    baseDomain: ocpdemo.labs
    clusterInstallRef:
        group: extensions.hive.openshift.io
        kind: AgentClusterInstall
        name: ztp-sno
        version: v1beta1
    clusterName: ztp-sno
    platform:
        agentBareMetal:
            agentSelector:
                matchLabels:
                    cluster-name: ztp-sno
    pullSecretRef:
        name: ztp-sno-pull-secret

---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "1"
        ran.openshift.io/ztp-gitops-generated: '{}'
    labels:
        nmstate-label: ztp-sno
    name: ztp-sno
    namespace: ztp-sno
spec:
    config:
        interfaces:
            - ipv4:
                auto-dns: true
                auto-gateway: true
                auto-route: true
                dhcp: true
                enabled: true
              name: enp1s0
              state: up
              type: ethernet
    interfaces:
        - name: enp1s0
          macAddress: 52:54:00:af:d6:bf

---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "1"
        ran.openshift.io/ztp-gitops-generated: '{}'
    name: ztp-sno
    namespace: ztp-sno
spec:
    additionalNTPSources:
        - time.google.com
        - time1.google.com
        - time2.google.com
    clusterRef:
        name: ztp-sno
        namespace: ztp-sno
    nmStateConfigLabelSelector:
        matchLabels:
            nmstate-label: ztp-sno
    pullSecretRef:
        name: ztp-sno-pull-secret
    sshAuthorizedKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC3aLYapMApL1taw0SeWysvpKOJf0tklEE20UtdBlIh9/S8oOZMf7qX+57PMJ82S/9tIAWcVnGQlErMkdPozF5CUjeNwrlOUVuKlYDwbz3olUFvnwF9a3xDw7RFm1oKyBaA/69eff7qSGWULwDiVH4CRO1EVvQlOsONz/oT4hcLkJMAoCyWeKBgHfpS30kVTnk0+qh5Xu7tEwr8yf/CIfJFO1n39lP9htpnUnGXPeMfXApN0YE7XXZXt8x50DlsqfVc+1u/EaIDwSwTYH7VYba/LpS8Coa4Ox7r98kHq+VxYU3g546b7RgxCGgRFCYEnzDVW7BRM03UJJH1kOFJ1/954LomTSDVTgs7/fDhj3TmzEdKC74mE2MjuQs5HzsrHOyfswScHF5AhciXLFIy8FciJfm/+7iGfo2Kt/YUajdq9Tl6pjbmaNSSCYFxMQkPF9G2bZer0UBu1zMv5LG4r9Lrzc4wkl90O41Us7Bku983PFfwF9PTrnknDYy4vq2Mhm0vkJV8fGL9eyaZTwMmSE8W/3BOr6SY6pC//7qlHNbIbsBlTMQp2Tl6AleHOa5fbJN4D/7Ps5E+aL0aH8jdr6OMxOSrc6w1DJg5x3paZ59zqdiQ+Ybnu0Vkts7KxbKCsaPJjA5jwIL5FSoZsjUMXcdOrUyLova6/M7DYZut7qHNrQ== '

---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "1"
        bmac.agent-install.openshift.io/hostname: ztp-sno
        bmac.agent-install.openshift.io/role: master
        inspect.metal3.io: disabled
        ran.openshift.io/ztp-gitops-generated: '{}'
    labels:
        infraenvs.agent-install.openshift.io: ztp-sno
    name: ztp-sno
    namespace: ztp-sno
spec:
    automatedCleaningMode: disabled
    bmc:
        address: redfish-virtualmedia+https://95.216.68.250:8000/redfish/v1/Systems/55369357-97e3-40c3-8560-e1d643876a3f
        credentialsName: ztp-sno-bmc-credentials
        disableCertificateVerification: true
    bootMACAddress: 52:54:00:af:d6:bf
    bootMode: UEFI
    online: true

---
apiVersion: v1
data: {}
kind: ConfigMap
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "1"
        ran.openshift.io/ztp-gitops-generated: '{}'
    name: ztp-sno
    namespace: ztp-sno

---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "2"
        ran.openshift.io/ztp-gitops-generated: '{}'
    labels:
        sites: ztp-sno
    name: ztp-sno
spec:
    hubAcceptsClient: true

---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "2"
        ran.openshift.io/ztp-gitops-generated: '{}'
    name: ztp-sno
    namespace: ztp-sno
spec:
    applicationManager:
        enabled: true
    certPolicyController:
        enabled: true
    clusterLabels:
        cloud: Baremetal
        vendor: auto-detect
    clusterName: ztp-sno
    clusterNamespace: ztp-sno
    iamPolicyController:
        enabled: true
    policyController:
        enabled: true
    searchCollector:
        enabled: true

