---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: ztp-sno
  namespace: ztp-sno
spec:
  baseDomain: ocpdemo.labs
  pullSecretRef:
    name: "ztp-sno-pull-secret"
  clusterImageSetNameRef: "openshift-4.12"
  sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC3aLYapMApL1taw0SeWysvpKOJf0tklEE20UtdBlIh9/S8oOZMf7qX+57PMJ82S/9tIAWcVnGQlErMkdPozF5CUjeNwrlOUVuKlYDwbz3olUFvnwF9a3xDw7RFm1oKyBaA/69eff7qSGWULwDiVH4CRO1EVvQlOsONz/oT4hcLkJMAoCyWeKBgHfpS30kVTnk0+qh5Xu7tEwr8yf/CIfJFO1n39lP9htpnUnGXPeMfXApN0YE7XXZXt8x50DlsqfVc+1u/EaIDwSwTYH7VYba/LpS8Coa4Ox7r98kHq+VxYU3g546b7RgxCGgRFCYEnzDVW7BRM03UJJH1kOFJ1/954LomTSDVTgs7/fDhj3TmzEdKC74mE2MjuQs5HzsrHOyfswScHF5AhciXLFIy8FciJfm/+7iGfo2Kt/YUajdq9Tl6pjbmaNSSCYFxMQkPF9G2bZer0UBu1zMv5LG4r9Lrzc4wkl90O41Us7Bku983PFfwF9PTrnknDYy4vq2Mhm0vkJV8fGL9eyaZTwMmSE8W/3BOr6SY6pC//7qlHNbIbsBlTMQp2Tl6AleHOa5fbJN4D/7Ps5E+aL0aH8jdr6OMxOSrc6w1DJg5x3paZ59zqdiQ+Ybnu0Vkts7KxbKCsaPJjA5jwIL5FSoZsjUMXcdOrUyLova6/M7DYZut7qHNrQ== 
'
  clusters:
  - clusterName: ztp-sno
    networkType: "OVNKubernetes"
    clusterLabels:
      sites : ztp-sno
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 192.168.235.0/24
    serviceNetwork:
      - 172.30.0.0/16
    additionalNTPSources:
      - time.google.com
      - time1.google.com
      - time2.google.com
    crTemplates:
      KlusterletAddonConfig: "KlusterletAddonConfig.yaml"
    nodes:
      - hostName: "ztp-sno"
        role: "master"
        bmcAddress: "redfish-virtualmedia+https://95.216.68.250:8000/redfish/v1/Systems/d40267c0-39ff-4ea2-8759-399590249fe9"
        bmcCredentialsName:
          name: "ztp-sno-bmc-credentials"
        bootMACAddress: 52:54:00:7c:50:8a
        bootMode: "UEFI"
        nodeNetwork:
          interfaces:
            - name: enp1s0
              macAddress: 52:54:00:7c:50:8a
          config:
            interfaces:
              - name: enp1s0
                type: ethernet
                state: up
                ipv4:
                  enabled: true
                  dhcp: true
                  auto-dns: true
                  auto-gateway: true
                  auto-routes: true
